# Site settings
title: 03sunf
description: >
    03sunf's blog
author: 03sunf
email: 03sunf@gmail.com
baseurl: ""
url: "https://03sunf.github.io"
twitter_username: 03sunf
github_username:  03sunf
disqus_shortname: blog-03sunf-com

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
